import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import request from 'supertest';
import { setupTestEnvironment, teardownTestEnvironment } from './helpers/test-env.js';
const dir = await setupTestEnvironment({ FILE_SIZE_LIMIT_MB: 0, IMAGE_SIZE_LIMIT_MB: 0, FILE_COUNT_LIMIT: 1 });
const { createApp } = await import('../server/app.js');
const { closeDatabase } = await import('../server/database.js');
const app = await createApp();
test.after(async () => { closeDatabase(); await teardownTestEnvironment(dir); });
test('unlimited mode streams a file beyond the former 25 MiB limit, preserves bytes and cleans rejected temporary uploads', async () => {
  const source = path.join(dir, 'large.dat');
  const handle = await fs.open(source, 'w');
  await handle.truncate(26 * 1024 * 1024);
  await handle.write(Buffer.from('last bytes'), 0, 10, 26 * 1024 * 1024 - 10);
  await handle.close();
  const uploaded = await request(app).post('/api/files').attach('file', source);
  assert.equal(uploaded.status, 201);
  assert.equal(uploaded.body.file.sizeBytes, 26 * 1024 * 1024);
  const stored = await fs.readdir(path.join(dir, 'files'));
  const saved = await fs.readFile(path.join(dir, 'files', stored[0]));
  assert.equal(saved.subarray(-10).toString(), 'last bytes');
  assert.deepEqual(await fs.readdir(path.join(dir, 'incoming')), []);
  const rejected = await request(app).post('/api/files').attach('file', Buffer.from('overflow'), 'extra.txt');
  assert.equal(rejected.status, 409);
  assert.deepEqual(await fs.readdir(path.join(dir, 'incoming')), []);
  const state = await request(app).get('/api/state');
  assert.equal(state.body.limits.fileSizeLimitBytes, 0);
  assert.equal(state.body.limits.imageSizeLimitBytes, 0);
});
